apiVersion: v1
kind: Pod
metadata:
  name: gcp-vol-pod
spec:
  containers:
  - image: mongo             
    name: mongo
    volumeMounts:                          
    - name: gcpvol
      mountPath: /data/db     
    ports:
    - containerPort: 27017
      protocol: TCP
  volumes:                                 
  - name: gcpvol
    gcePersistentDisk:
      pdName: mongodb
      fsType: ext4
