apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv2
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany  
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: mongodb1
    fsType: ext4
