kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-pvc1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
